version: "3"
services:
  mongo:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PASSWORD
    - MONGO_INITDB_DATABASE=$MONGO_DB_NAME
    - MONGO_DB_PORT=$MONGO_DB_PORT
    ports:
    - $MONGO_DB_PORT:$MONGO_DB_PORT
    expose:
    - $MONGO_DB_PORT
  omniboard:
    command: ["--mu", "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo:${MONGO_DB_PORT}/db?authSource=admin", "${MONGO_DB_NAME}"]
    ports:
    - $OMNIBOARD_PORT:$OMNIBOARD_PORT