version: "3"
services:
  mongo:
    image: mongo
    networks:
      - sacred
  omniboard:
    image: vivekratnavel/omniboard
    networks:
      - sacred
    depends_on:
      - mongo
networks:
  sacred: